[package]
name = "first_opengl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.1"
gl = "0.14.0"
glfw = "0.43.0"